# Generated by Django 4.2.8 on 2023-12-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='spamreport',
            old_name='phone_number',
            new_name='reported_number',
        ),
    ]
