# Generated by Django 4.2.8 on 2023-12-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spam', '0002_remove_contact_user_remove_userprofile_user_and_more'),
        ('users', '0002_user_remove_userprofile_user_delete_spamreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
